#!/bin/sh

UUID_ROOT=$(findmnt -no UUID ./mnt)
UUID_BOOT=$(findmnt -no UUID ./mnt/boot)

NFS_OPTIONS="defaults,rdma,_netdev,noatime,x-systemd.device-timeout=10"

PATERN="%s\t%s\t%s\t%s\t%s\t%s"

BOOT=$(printf "$PATERN" "UUID=$UUID_BOOT" "/boot" "vfat" "defaults,umask=027" "0" "2")
ROOT=$(printf "$PATERN" "UUID=$UUID_ROOT" "/" "btrfs" "defaults" "0" "1")

if [ -n "$NFS_SERVER" ]; then
    HOME=$(printf "$PATERN" "$NFS_SERVER:/home" "/home" "nfs" "$NFS_OPTIONS" "0" "0")
    OPT=$(printf "$PATERN" "$NFS_SERVER:/opt" "/opt" "nfs" "$NFS_OPTIONS" "0" "0")
    MNT=$(printf "$PATERN" "$NFS_SERVER:/mnt/niuniu" "/mnt/niuniu" "nfs" "$NFS_OPTIONS" "0" "0")
    FSTAB="$BOOT\n$ROOT\n$HOME\n$OPT\n$MNT"
else
    FSTAB="$BOOT\n$ROOT"
fi

cat <<EOF
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a device;
# this may be used with UUID= as a more robust way to name devices that
# works even if disks are added and removed. See fstab(5).
#
# <file system>  <mount point>  <type>  <options>  <dump>  <pass>
$FSTAB
EOF
