#!/bin/sh

UUID_ROOT=$(findmnt -no UUID ./mnt)
UUID_BOOT=$(findmnt -no UUID ./mnt/boot)

NFS_OPTIONS="defaults,rdma,_netdev,noatime,x-systemd.device-timeout=10"

PATERN="%s\t%s\t%s\t%s\t%s\t%s"

BOOT=$(printf "$PATERN" "UUID=$UUID_BOOT" "/boot" "vfat" "defaults,umask=027" "0" "2")
ROOT=$(printf "$PATERN" "UUID=$UUID_ROOT" "/" "btrfs" "defaults" "0" "1")
HOME=$(printf "$PATERN" "10.0.0.0:/home" "/home" "nfs" "$NFS_OPTIONS" "0" "0")
OPT=$(printf "$PATERN" "10.0.0.0:/opt" "/opt" "nfs" "$NFS_OPTIONS" "0" "0")
MNT=$(printf "$PATERN" "10.0.0.0:/mnt/niuniu" "/mnt/niuniu" "nfs" "$NFS_OPTIONS" "0" "0")

if SSH_SERVER
cat <<EOF
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a device;
# this may be used with UUID= as a more robust way to name devices that
# works even if disks are added and removed. See fstab(5).
#
# <file system>  <mount point>  <type>  <options>  <dump>  <pass>
$BOOT
$ROOT
$HOME
$OPT
$MNT
EOF
